version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: rusanorder-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rusanorder
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
